# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chirp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Chirp
  pod 'MobileCenter/Crashes', '~> 0.13.0'
  pod 'MobileCenter/Analytics', '~> 0.13.0'
  pod 'RNMobileCenterShared', '~> 0.10.0'

  

  target 'ChirpTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Chirp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Chirp-tvOS

  target 'Chirp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
